In [1]:
import torch
from torch.utils.data import DataLoader
from torch.utils.data.dataset import Dataset
from torchvision import datasets, transforms

# DataSet

In [2]:
class SquareDataset(Dataset):
    def __init__(self, size):
        self.size = size
        self.X = torch.randint(255, (size, 9), dtype=torch.float)

        real_w = torch.tensor([[1,1,1,0,0,0,0,0,0],
                               [0,0,0,1,1,1,0,0,0],
                               [0,0,0,0,0,0,1,1,1]], 
                               dtype=torch.float)

        y = torch.argmax(self.X.mm(real_w.t()), 1)
        
        self.Y = torch.zeros(size, 3, dtype=torch.float) \
                      .scatter_(1, y.view(-1, 1), 1)

    def __getitem__(self, index):
        return (self.X[index], self.Y[index])

    def __len__(self):
        return self.size

In [3]:
squares = SquareDataset(256)
print(squares[34])
print(squares[254])
print(squares[25])

(tensor([132.,  82.,  47., 101., 161., 133.,  35., 181., 244.]), tensor([0., 0., 1.]))
(tensor([159., 159., 174., 139.,  43., 216.,  80., 136., 226.]), tensor([1., 0., 0.]))
(tensor([ 93.,  87.,  64., 254., 225., 152., 131.,  28., 175.]), tensor([0., 1., 0.]))


In [4]:
dataloader = DataLoader(squares, batch_size=5)

for batch, (X, Y) in enumerate(dataloader):
    print(X, '\n\n', Y)
    break

tensor([[179., 168., 174.,   5.,  78., 103., 196., 214., 210.],
        [133., 161., 190.,   5., 227., 245., 189., 152.,  22.],
        [170.,  36.,  14., 175., 111.,  13., 144., 118., 105.],
        [ 29., 224., 220., 203., 132.,  96.,  24., 215., 164.],
        [141., 254.,  92., 203., 152., 171.,  32., 253.,  97.]]) 

 tensor([[0., 0., 1.],
        [1., 0., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]])
