In [1]:
import torch
from torch.utils.data import DataLoader
from torch.utils.data.dataset import Dataset
from torchvision import datasets, transforms

# DataSet

In [2]:
class SquareDataset(Dataset):
    def __init__(self, size):
        self.size = size
        self.X = torch.randint(255, (size, 9), dtype=torch.float)

        real_w = torch.tensor([[1,1,1,0,0,0,0,0,0],
                               [0,0,0,1,1,1,0,0,0],
                               [0,0,0,0,0,0,1,1,1]], 
                               dtype=torch.float)

        y = torch.argmax(self.X.mm(real_w.t()), 1)
        
        self.Y = torch.zeros(size, 3, dtype=torch.float) \
                      .scatter_(1, y.view(-1, 1), 1)

    def __getitem__(self, index):
        return (self.X[index], self.Y[index])

    def __len__(self):
        return self.size

In [3]:
squares = SquareDataset(256)
print(squares[34])
print(squares[254])
print(squares[25])

(tensor([ 21.,  31., 235., 196., 169.,  30.,  12.,  87., 242.]), tensor([0., 1., 0.]))
(tensor([ 35.,  49., 248., 190., 154., 160., 207.,  89.,  28.]), tensor([0., 1., 0.]))
(tensor([183.,  18., 240., 199.,  84., 139., 171., 128., 246.]), tensor([0., 0., 1.]))


In [4]:
dataloader = DataLoader(squares, batch_size=5)

for batch, (X, Y) in enumerate(dataloader):
    print(X, '\n\n', Y)
    break

tensor([[161., 227.,  90., 174., 200., 200.,  36., 204., 231.],
        [135.,  95.,  41.,  67., 214.,  62., 146., 123.,  41.],
        [169.,  38.,  10., 237.,  70., 220., 215., 125.,  98.],
        [  8.,  27.,   8.,  56., 237.,  92.,  40.,  15., 128.],
        [136., 250., 224., 227., 155.,  32., 178., 118., 236.]]) 

 tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])


In [7]:
for x, y in dataloader:
    print(x)
    print(y)
    break

tensor([[161., 227.,  90., 174., 200., 200.,  36., 204., 231.],
        [135.,  95.,  41.,  67., 214.,  62., 146., 123.,  41.],
        [169.,  38.,  10., 237.,  70., 220., 215., 125.,  98.],
        [  8.,  27.,   8.,  56., 237.,  92.,  40.,  15., 128.],
        [136., 250., 224., 227., 155.,  32., 178., 118., 236.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])
